--- !ditz.rubyforge.org,2008-03-06/project 
name: doodle
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: doodle
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: examples
- !ditz.rubyforge.org,2008-03-06/component 
  name: docs
- !ditz.rubyforge.org,2008-03-06/component 
  name: extras
- !ditz.rubyforge.org,2008-03-06/component 
  name: packaging
- !ditz.rubyforge.org,2008-03-06/component 
  name: project
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: r0.2.0
  status: :released
  release_time: 2009-03-02 10:43:27.030549 Z
  log_events: 
  - - 2009-02-15 13:28:12.779752 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - created
    - ""
  - - 2009-03-02 10:43:27.030562 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: r0.3.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-02-24 10:40:37.526900 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - created
    - aiming for 1.8.7, 1.9.1, JRuby and Rubinius compatibility
- !ditz.rubyforge.org,2008-03-06/release 
  name: r1.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-02-24 10:37:18.487877 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - created
    - |-
      First feature complete release
      - need to define what I consider the full set of features :)
      - compatible across ruby 1.8.6, 1.8.7, 1.9.x, JRuby, Rubinius?
      - tidied up
      - full docs (again that word 'full')
        - every feature documented
        - example for every feature
      - full set of examples
      - rdoc-friendly
