--- !ditz.rubyforge.org,2008-03-06/project 
name: doodle
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: doodle
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: examples
- !ditz.rubyforge.org,2008-03-06/component 
  name: docs
- !ditz.rubyforge.org,2008-03-06/component 
  name: extras
releases: []

